apiVersion: mindxdl.gitee.com/v1
kind: AscendJob
metadata:
  name: default-infer-test-pytorch-npu
  labels:
    framework: pytorch
    fault-scheduling: "force"
    fault-retry-times: "10"
    huawei.com/scheduler.softShareDev.aicoreQuota: "50" # soft share device core quota, unit: %
    huawei.com/scheduler.softShareDev.hbmQuota: "2048" # soft share device hbm quota, unit: MB
    huawei.com/scheduler.softShareDev.policy: "fixed-share" # 1:fixed-share 2:elastic 3:best-effort
  annotations:
    huawei.com/schedule_policy: "chip1-softShareDev" # soft share device volcano schedule policy
spec:
  schedulerName: volcano   # work when enableGangScheduling is true
  runPolicy:
    schedulingPolicy:      # work when enableGangScheduling is true
      minAvailable: 2 # soft share dev tasks with multiple replicas are only supported for single-machine scenarios.
      queue: default
  successPolicy: AllWorkers
  replicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          automountServiceAccountToken: false
          containers:
            - name: ascend # do not modify
              image: pytorch-test:latest         # training framework image， which can be modified
              imagePullPolicy: IfNotPresent
              env:
                - name: XDL_IP                                       # IP address of the physical node, which is used to identify the node where the pod is running
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
              command:                           # training command, which can be modified
                - /bin/bash
                - -c
              args: [ "./infer.sh" ]
              ports:                          # default value containerPort: 2222 name: ascendjob-port if not set
                - containerPort: 2222         # determined by user
                  name: ascendjob-port        # do not modify
              resources:
                requests:
                  huawei.com/npu: 50 # should be equal to huawei.com/scheduler.softShareDev.aicoreQuota
                limits:
                  huawei.com/npu: 50 # should be equal to huawei.com/scheduler.softShareDev.aicoreQuota
              volumeMounts:
                - name: ascend-driver
                  mountPath: /usr/local/Ascend/driver
                - name: ascend-add-ons
                  mountPath: /usr/local/Ascend/add-ons
                - name: dshm
                  mountPath: /dev/shm
                - name: localtime
                  mountPath: /etc/localtime
                - name: libpreload # soft split dynamic library path
                  mountPath: /opt/enpu/vcann-rt/lib/libvruntime.so
                - name: preload # preload configuration file path
                  mountPath: /etc/ld.so.preload
          volumes:
            - name: ascend-driver
              hostPath:
                path: /usr/local/Ascend/driver
            - name: ascend-add-ons
              hostPath:
                path: /usr/local/Ascend/add-ons
            - name: dshm
              emptyDir:
                medium: Memory
            - name: localtime
              hostPath:
                path: /etc/localtime
            - name: libpreload # soft split dynamic library path
              hostPath:
                path: /opt/enpu/vcann-rt/lib/libvruntime.so
            - name: preload # The path of the ld.so.preload file on the host side is user-customizable. In subsequent document content, ${preload_path} is used to represent this path. Inside the container, the path is fixed as /etc/ld.so.preload. It is not recommended to place the ld.so.preload file in the host’s /etc directory, as this would preload the soft‑shared dynamic library on the host side and may interfere with host‑side services.
              hostPath:
                path: ${preload_path}/ld.so.preload
    Worker:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          automountServiceAccountToken: false
          containers:
            - name: ascend # do not modify
              image: pytorch-test:latest         # training framework image， which can be modified
              imagePullPolicy: IfNotPresent
              env:
                - name: XDL_IP                                       # IP address of the physical node, which is used to identify the node where the pod is running
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
              command: # training command, which can be modified
                - /bin/bash
                - -c
              args: [ "./infer.sh" ]
              ports: # default value containerPort: 2222 name: ascendjob-port if not set
                - containerPort: 2222         # determined by user
                  name: ascendjob-port        # do not modify
              resources:
                requests:
                  huawei.com/npu: 50 # should be equal to huawei.com/scheduler.softShareDev.aicoreQuota
                limits:
                  huawei.com/npu: 50 # should be equal to huawei.com/scheduler.softShareDev.aicoreQuota
              volumeMounts:
                - name: ascend-driver
                  mountPath: /usr/local/Ascend/driver
                - name: ascend-add-ons
                  mountPath: /usr/local/Ascend/add-ons
                - name: dshm
                  mountPath: /dev/shm
                - name: localtime
                  mountPath: /etc/localtime
                - name: libpreload # soft split dynamic library path
                  mountPath: /opt/enpu/vcann-rt/lib/libvruntime.so
                - name: preload # preload configuration file path
                  mountPath: /etc/ld.so.preload
          volumes:
            - name: ascend-driver
              hostPath:
                path: /usr/local/Ascend/driver
            - name: ascend-add-ons
              hostPath:
                path: /usr/local/Ascend/add-ons
            - name: dshm
              emptyDir:
                medium: Memory
            - name: localtime
              hostPath:
                path: /etc/localtime
            - name: libpreload # soft split dynamic library path
              hostPath:
                path: /opt/enpu/vcann-rt/lib/libvruntime.so
            - name: preload # The path of the ld.so.preload file on the host side is user-customizable. In subsequent document content, ${preload_path} is used to represent this path. Inside the container, the path is fixed as /etc/ld.so.preload. It is not recommended to place the ld.so.preload file in the host’s /etc directory, as this would preload the soft‑shared dynamic library on the host side and may interfere with host‑side services.
              hostPath:
                path: ${preload_path}/ld.so.preload
